# Education Project: Socioeconomic Factors Associated with ACT Scores | Data Preparation

## Project Introduction
This project analyses the relationship between socio-economic factors and student ACT scores. We will be looking at various factors like median income, unemployment rate, household status, college attainment  as well as participation in free or reductd lunch are associated with student academic performance.

## Import Libraries and Dataset

In [1]:
# Import pandas, numpy, and matplotlib
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# seaborn is a data visualization library built on matplotlib
import seaborn as sns

# set the plotting style
sns.set_style("whitegrid")

In [2]:
# Since source data has been stored in the project Data folder, we will save the path to our dataset for reproducability. 
from pathlib import Path

DATA_DIR = Path('../data')

edgap_path = DATA_DIR / 'EdGap_data.xlsx'
school_info_path = DATA_DIR / 'ccd_sch_029_1617_w_1a_11212017.csv'

### Edgap dataset
For the project, EdGap dataset that includes our primary socioeconomic factors was provided through canvas LMS. However, https://www.edgap.org/ is the original data store that stores publicly available collection of school level data on average sat and various socio-economic factors.

In [3]:
edgap_path

WindowsPath('../data/EdGap_data.xlsx')

In [4]:
# Here, we read the school ID as an object because it is an identifier, not a numerical measurement.
edgap = pd.read_excel(edgap_path,
                     dtype = {'NCESSCH School ID': object})

C:\Users\binay\anaconda3\Lib\site-packages\openpyxl\worksheet\_read_only.py:85: UserWarning: Unknown extension is not supported and will be removed
  for idx, row in parser.parse():

In [5]:
edgap.info()

<class 'pandas.DataFrame'>
RangeIndex: 7986 entries, 0 to 7985
Data columns (total 7 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   NCESSCH School ID                                7986 non-null   object
 1   CT Unemployment Rate                             7972 non-null   float64
 2   CT Pct Adults with College Degree                7973 non-null   float64
 3   CT Pct Childre In Married Couple Family          7961 non-null   float64
 4   CT Median Household Income                       7966 non-null   float64
 5   School ACT average (or equivalent if SAT score)  7986 non-null   float64
 6   School Pct Free and Reduced Lunch                7986 non-null   float64
dtypes: float64(6), object(1)
memory usage: 436.9+ KB

Key items to note from the Edgap dataset:
* Unemployment Rate could be used as predictor
* Percent adults with college degree as predictor
* Percent children in married family as predictor
* Median Household Income as predictor
* ACT average --> This is what we would like to predict. Dependent variable
* Percent of students receiving Free and reduced lunch as predictor
* Missing value --> Some missing value that needs to be addressed
* Data type --> We have addressed School Id. Rest seems to be fine.

### School Information Dataset
The school information dataset includes identifying information about individual schools. For this project, the dataset was obtained through Seattle University's course Canvas LMS. Original data source is  National Center for Education Statistics (https://nces.ed.gov/ccd/pubschuniv.asp).

In [6]:
# We specify the encoding here so Python can correctly read the characters in this CSV file.
school_information = pd.read_csv(school_info_path,
                                encoding = 'unicode_escape'
                                )

C:\Users\binay\AppData\Local\Temp\ipykernel_13120\1655727939.py:2: DtypeWarning: Columns (0: STATE_AGENCY_NO, 1: LEAID, 2: MSTREET2, 3: MSTREET3, 4: MZIP, 5: MZIP4, 6: LSTREET2, 7: LSTREET3, 8: LZIP, 9: LZIP4, 10: SY_STATUS, 11: UPDATED_STATUS, 12: SCH_TYPE, 13: CHARTAUTH1, 14: CHARTAUTH2, 15: CHARTAUTHN2) have mixed types. Specify dtype option on import or set low_memory=False.
  school_information = pd.read_csv(school_info_path,

In [7]:
school_information.info()

<class 'pandas.DataFrame'>
RangeIndex: 102183 entries, 0 to 102182
Data columns (total 65 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   SCHOOL_YEAR          102183 non-null  str
 1   FIPST                102183 non-null  int64
 2   STATENAME            102183 non-null  str
 3   ST                   102183 non-null  str
 4   SCH_NAME             102183 non-null  str
 5   LEA_NAME             102183 non-null  str
 6   STATE_AGENCY_NO      102183 non-null  object
 7   UNION                2533 non-null    float64
 8   ST_LEAID             102183 non-null  str
 9   LEAID                102183 non-null  object
 10  ST_SCHID             102183 non-null  str
 11  NCESSCH              102181 non-null  float64
 12  SCHID                102181 non-null  float64
 13  MSTREET1             102181 non-null  str
 14  MSTREET2             1825 non-null    str
 15  MSTREET3             28 non-null      str
 16  MCITY                102183 non-null  str
 17  MSTATE               102183 non-null  str
 18  MZIP                 102183 non-null  object
 19  MZIP4                60419 non-null   object
 20  LSTREET1             102183 non-null  str
 21  LSTREET2             582 non-null     str
 22  LSTREET3             13 non-null      str
 23  LCITY                102183 non-null  str
 24  LSTATE               102183 non-null  str
 25  LZIP                 102183 non-null  object
 26  LZIP4                59145 non-null   object
 27  PHONE                102183 non-null  str
 28  WEBSITE              51983 non-null   str
 29  SY_STATUS            102181 non-null  object
 30  SY_STATUS_TEXT       102181 non-null  str
 31  UPDATED_STATUS       102181 non-null  object
 32  UPDATED_STATUS_TEXT  102181 non-null  str
 33  EFFECTIVE_DATE       102181 non-null  str
 34  SCH_TYPE_TEXT        102181 non-null  str
 35  SCH_TYPE             102181 non-null  object
 36  RECON_STATUS         102181 non-null  str
 37  OUT_OF_STATE_FLAG    102179 non-null  str
 38  CHARTER_TEXT         102179 non-null  str
 39  CHARTAUTH1           6687 non-null    object
 40  CHARTAUTHN1          6687 non-null    str
 41  CHARTAUTH2           116 non-null     object
 42  CHARTAUTHN2          116 non-null     str
 43  NOGRADES             102179 non-null  str
 44  G_PK_OFFERED         102179 non-null  str
 45  G_KG_OFFERED         102179 non-null  str
 46  G_1_OFFERED          102179 non-null  str
 47  G_2_OFFERED          102179 non-null  str
 48  G_3_OFFERED          102179 non-null  str
 49  G_4_OFFERED          102179 non-null  str
 50  G_5_OFFERED          102179 non-null  str
 51  G_6_OFFERED          102179 non-null  str
 52  G_7_OFFERED          102179 non-null  str
 53  G_8_OFFERED          102179 non-null  str
 54  G_9_OFFERED          102179 non-null  str
 55  G_10_OFFERED         102179 non-null  str
 56  G_11_OFFERED         102179 non-null  str
 57  G_12_OFFERED         102179 non-null  str
 58  G_13_OFFERED         102179 non-null  str
 59  G_UG_OFFERED         102179 non-null  str
 60  G_AE_OFFERED         102179 non-null  str
 61  GSLO                 102179 non-null  str
 62  GSHI                 102179 non-null  str
 63  LEVEL                102179 non-null  str
 64  IGOFFERED            102179 non-null  str
dtypes: float64(3), int64(1), object(11), str(50)
memory usage: 78.6+ MB

In summary this dataset contains a lot of reference information about school. 
Key items to note from school information dataset:
* Volume of dataset. This dataset contains a significant number of columns and rows.
* It means Edgap dataset does not contain information for all schools listed in the school information dataset.
* We will be interested in descriptive values in columns LEVEL, CHARTER_TEXT.
* Additionally Geo location data points like STATE, CITY may be useful.
* Missing Values --> There are missing values. We would be interested in knowing if any data that needed to be joind with Edgap is missing. 
* Additional review is needed to understand relevant datapoints for analysis.

In [8]:
# Inspect school information dataset
school_information.head(5)

,SCHOOL_YEAR,FIPST,STATENAME,ST,SCH_NAME,LEA_NAME,STATE_AGENCY_NO,UNION,ST_LEAID,LEAID,...,G_10_OFFERED,G_11_OFFERED,G_12_OFFERED,G_13_OFFERED,G_UG_OFFERED,G_AE_OFFERED,GSLO,GSHI,LEVEL,IGOFFERED
0,2016-2017,1,ALABAMA,AL,Sequoyah Sch - Chalkville Campus,Alabama Youth Services,1,NaN,AL-210,100002,...,Yes,Yes,Yes,No,No,No,07,12,High,As reported
1,2016-2017,1,ALABAMA,AL,Camps,Alabama Youth Services,1,NaN,AL-210,100002,...,Yes,Yes,Yes,No,No,No,07,12,High,As reported
2,2016-2017,1,ALABAMA,AL,Det Ctr,Alabama Youth Services,1,NaN,AL-210,100002,...,Yes,Yes,Yes,No,No,No,07,12,High,As reported
3,2016-2017,1,ALABAMA,AL,Wallace Sch - Mt Meigs Campus,Alabama Youth Services,1,NaN,AL-210,100002,...,Yes,Yes,Yes,No,No,No,07,12,High,As reported
4,2016-2017,1,ALABAMA,AL,McNeel Sch - Vacca Campus,Alabama Youth Services,1,NaN,AL-210,100002,...,Yes,Yes,Yes,No,No,No,07,12,High,As reported

Since we can not see all columns when we look at the .head(), we can update the default option so we can display all columns.

In [9]:
pd.set_option('display.max_columns', None)
school_information.head()

,SCHOOL_YEAR,FIPST,STATENAME,ST,SCH_NAME,LEA_NAME,STATE_AGENCY_NO,UNION,ST_LEAID,LEAID,ST_SCHID,NCESSCH,SCHID,MSTREET1,MSTREET2,MSTREET3,MCITY,MSTATE,MZIP,MZIP4,LSTREET1,LSTREET2,LSTREET3,LCITY,LSTATE,LZIP,LZIP4,PHONE,WEBSITE,SY_STATUS,SY_STATUS_TEXT,UPDATED_STATUS,UPDATED_STATUS_TEXT,EFFECTIVE_DATE,SCH_TYPE_TEXT,SCH_TYPE,RECON_STATUS,OUT_OF_STATE_FLAG,CHARTER_TEXT,CHARTAUTH1,CHARTAUTHN1,CHARTAUTH2,CHARTAUTHN2,NOGRADES,G_PK_OFFERED,G_KG_OFFERED,G_1_OFFERED,G_2_OFFERED,G_3_OFFERED,G_4_OFFERED,G_5_OFFERED,G_6_OFFERED,G_7_OFFERED,G_8_OFFERED,G_9_OFFERED,G_10_OFFERED,G_11_OFFERED,G_12_OFFERED,G_13_OFFERED,G_UG_OFFERED,G_AE_OFFERED,GSLO,GSHI,LEVEL,IGOFFERED
0,2016-2017,1,ALABAMA,AL,Sequoyah Sch - Chalkville Campus,Alabama Youth Services,1,NaN,AL-210,100002,AL-210-0020,1.000020e+10,100277.0,P O Box 9486,NaN,NaN,Birmingham,AL,35220,NaN,1000 Industrial School Road,NaN,NaN,Birmingham,AL,35220,NaN,(205)680-8574,http://www.dys.alabama.gov,1,Open,1,Open,03/03/2010,Alternative School,4,No,No,No,NaN,NaN,NaN,NaN,No,No,No,No,No,No,No,No,No,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,07,12,High,As reported
1,2016-2017,1,ALABAMA,AL,Camps,Alabama Youth Services,1,NaN,AL-210,100002,AL-210-0050,1.000020e+10,101667.0,P O Box 66,NaN,NaN,Mt Meigs,AL,36057,NaN,1601 County Rd. 57,NaN,NaN,Prattville,AL,36067,NaN,(334)215-3850,http://www.dys.alabama.gov,1,Open,1,Open,03/03/2010,Alternative School,4,No,No,No,NaN,NaN,NaN,NaN,No,No,No,No,No,No,No,No,No,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,07,12,High,As reported
2,2016-2017,1,ALABAMA,AL,Det Ctr,Alabama Youth Services,1,NaN,AL-210,100002,AL-210-0060,1.000020e+10,101670.0,P O Box 66,NaN,NaN,Mt Meigs,AL,36057,NaN,2109 Bashi Rd Bldg 509,NaN,NaN,Thomasville,AL,36784,NaN,(334)215-3850,http://www.dys.alabama.gov,1,Open,1,Open,03/03/2010,Alternative School,4,No,No,No,NaN,NaN,NaN,NaN,No,No,No,No,No,No,No,No,No,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,07,12,High,As reported
3,2016-2017,1,ALABAMA,AL,Wallace Sch - Mt Meigs Campus,Alabama Youth Services,1,NaN,AL-210,100002,AL-210-0030,1.000020e+10,101705.0,P O Box 66,NaN,NaN,Mount Meigs,AL,36057,NaN,1000 Industrial School Road,NaN,NaN,Mount Meigs,AL,36057,NaN,(334)215-6039,http://www.dys.alabama.gov,1,Open,1,Open,03/03/2010,Alternative School,4,No,No,No,NaN,NaN,NaN,NaN,No,No,No,No,No,No,No,No,No,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,07,12,High,As reported
4,2016-2017,1,ALABAMA,AL,McNeel Sch - Vacca Campus,Alabama Youth Services,1,NaN,AL-210,100002,AL-210-0040,1.000020e+10,101706.0,8950 Roebuck Blvd,NaN,NaN,Birmingham,AL,35206,NaN,8950 Roebuck Blvd,NaN,NaN,Birmingham,AL,35206,NaN,(205)838-4981,http://www.dys.alabama.gov,1,Open,1,Open,03/03/2010,Alternative School,4,No,No,No,NaN,NaN,NaN,NaN,No,No,No,No,No,No,No,No,No,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,07,12,High,As reported

In [10]:
school_information.columns

Index(['SCHOOL_YEAR', 'FIPST', 'STATENAME', 'ST', 'SCH_NAME', 'LEA_NAME',
       'STATE_AGENCY_NO', 'UNION', 'ST_LEAID', 'LEAID', 'ST_SCHID', 'NCESSCH',
       'SCHID', 'MSTREET1', 'MSTREET2', 'MSTREET3', 'MCITY', 'MSTATE', 'MZIP',
       'MZIP4', 'LSTREET1', 'LSTREET2', 'LSTREET3', 'LCITY', 'LSTATE', 'LZIP',
       'LZIP4', 'PHONE', 'WEBSITE', 'SY_STATUS', 'SY_STATUS_TEXT',
       'UPDATED_STATUS', 'UPDATED_STATUS_TEXT', 'EFFECTIVE_DATE',
       'SCH_TYPE_TEXT', 'SCH_TYPE', 'RECON_STATUS', 'OUT_OF_STATE_FLAG',
       'CHARTER_TEXT', 'CHARTAUTH1', 'CHARTAUTHN1', 'CHARTAUTH2',
       'CHARTAUTHN2', 'NOGRADES', 'G_PK_OFFERED', 'G_KG_OFFERED',
       'G_1_OFFERED', 'G_2_OFFERED', 'G_3_OFFERED', 'G_4_OFFERED',
       'G_5_OFFERED', 'G_6_OFFERED', 'G_7_OFFERED', 'G_8_OFFERED',
       'G_9_OFFERED', 'G_10_OFFERED', 'G_11_OFFERED', 'G_12_OFFERED',
       'G_13_OFFERED', 'G_UG_OFFERED', 'G_AE_OFFERED', 'GSLO', 'GSHI', 'LEVEL',
       'IGOFFERED'],
      dtype='str')

In [11]:
# select columns that will be useful from school information dataset
school_information = school_information[['SCHOOL_YEAR', 'NCESSCH', 'LSTATE', 'LZIP', 'SCH_TYPE_TEXT', 'LEVEL', 'CHARTER_TEXT', 'G_12_OFFERED']]

In [12]:
# Check school information after transformation
school_information.head()

,SCHOOL_YEAR,NCESSCH,LSTATE,LZIP,SCH_TYPE_TEXT,LEVEL,CHARTER_TEXT,G_12_OFFERED
0,2016-2017,1.000020e+10,AL,35220,Alternative School,High,No,Yes
1,2016-2017,1.000020e+10,AL,36067,Alternative School,High,No,Yes
2,2016-2017,1.000020e+10,AL,36784,Alternative School,High,No,Yes
3,2016-2017,1.000020e+10,AL,36057,Alternative School,High,No,Yes
4,2016-2017,1.000020e+10,AL,35206,Alternative School,High,No,Yes

In [13]:
# Inspect Edgap columns
edgap.columns

Index(['NCESSCH School ID', 'CT Unemployment Rate',
       'CT Pct Adults with College Degree',
       'CT Pct Childre In Married Couple Family', 'CT Median Household Income',
       'School ACT average (or equivalent if SAT score)',
       'School Pct Free and Reduced Lunch'],
      dtype='str')

In [14]:
# Inspect School Information columns
school_information.columns

Index(['SCHOOL_YEAR', 'NCESSCH', 'LSTATE', 'LZIP', 'SCH_TYPE_TEXT', 'LEVEL',
       'CHARTER_TEXT', 'G_12_OFFERED'],
      dtype='str')

## Data Cleansing

### Rename Columns
We will rename columns for both EdGap and school information for convinience and intuitive analysis

In [15]:
edgap = edgap.rename(
    columns={'NCESSCH School ID': 'id', 
             'CT Pct Adults with College Degree': 'percent_college' ,
             'CT Unemployment Rate': 'rate_unemployment' ,
             'CT Pct Childre In Married Couple Family': 'percent_married', 
             'CT Median Household Income':'median_income',
             'School ACT average (or equivalent if SAT score)':'average_act',
             'School Pct Free and Reduced Lunch':'percent_lunch',
            })

In [16]:
school_information = school_information.rename(
    columns={ 'SCHOOL_YEAR': 'year', 
              'NCESSCH': 'id', 
              'LSTATE': 'state', 
              'LZIP': 'zip_code', 
              'SCH_TYPE_TEXT': 'school_type', 
              'LEVEL': 'school_level',
              'CHARTER_TEXT': 'charter',
              'G_12_OFFERED': 'grade_12_offered',# MISSING THIS ATTRIBUTE
})

In [17]:
# Using df.info() method to inspect data types, count of non-null values and cloumns
edgap.info()

<class 'pandas.DataFrame'>
RangeIndex: 7986 entries, 0 to 7985
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 7986 non-null   object
 1   rate_unemployment  7972 non-null   float64
 2   percent_college    7973 non-null   float64
 3   percent_married    7961 non-null   float64
 4   median_income      7966 non-null   float64
 5   average_act        7986 non-null   float64
 6   percent_lunch      7986 non-null   float64
dtypes: float64(6), object(1)
memory usage: 436.9+ KB

In [18]:
school_information.info()

<class 'pandas.DataFrame'>
RangeIndex: 102183 entries, 0 to 102182
Data columns (total 8 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   year              102183 non-null  str
 1   id                102181 non-null  float64
 2   state             102183 non-null  str
 3   zip_code          102183 non-null  object
 4   school_type       102181 non-null  str
 5   school_level      102179 non-null  str
 6   charter           102179 non-null  str
 7   grade_12_offered  102179 non-null  str
dtypes: float64(1), object(1), str(6)
memory usage: 10.1+ MB

### Convert Data Type
We need to covnert data type of id column in school information dataset to type object. We do this so pandas does not treat id column as a numerical. There is a risk where values may be transformed. For example 000012 can be treated as simply 12, which in this case as this is a unique identifyer would be incorrect.

In [19]:
# Using Series.astype() method to update datatype to object
school_information['id'] = school_information['id'].astype('object')

In [20]:
school_information.info()

<class 'pandas.DataFrame'>
RangeIndex: 102183 entries, 0 to 102182
Data columns (total 8 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   year              102183 non-null  str
 1   id                102181 non-null  object
 2   state             102183 non-null  str
 3   zip_code          102183 non-null  object
 4   school_type       102181 non-null  str
 5   school_level      102179 non-null  str
 6   charter           102179 non-null  str
 7   grade_12_offered  102179 non-null  str
dtypes: object(2), str(6)
memory usage: 10.1+ MB

### Investigate Missing Values
Investigate missing values from both dataset

In [21]:
edgap.isna().sum()

id                    0
rate_unemployment    14
percent_college      13
percent_married      25
median_income        20
average_act           0
percent_lunch         0
dtype: int64

In [22]:
school_information.isna().sum()

year                0
id                  2
state               0
zip_code            0
school_type         2
school_level        4
charter             4
grade_12_offered    4
dtype: int64

We do not a significant number of missing values in either of our dataset. One thing to note is missing 'id' in school_information dataset. We may have to address this potentially.

Inspect Duplicate Values in 'id' field

In [23]:
edgap['id'].duplicated().sum()

np.int64(0)

In [24]:
school_information['id'].duplicated().sum()

np.int64(1)

The duplicated 'id' in school_information could be the missing items.

In [25]:
school_information[ school_information['id'].isna()]

,year,id,state,zip_code,school_type,school_level,charter,grade_12_offered
94051,hswebb\index.htm,NaN,No,Yes,12,NaN,NaN,NaN
94053,ces\index.html,NaN,Yes,No,07,NaN,NaN,NaN

We are not going to worry about the missing id fields as a significant number of rows from the school_information will be filter after we merge with the edgap dataset.

### Merge Datasets
We will be consolicating both dataset into a unified dataframe object for further analysis.

In [26]:
df = edgap.merge(school_information, how='left', on='id')
df.head()

,id,rate_unemployment,percent_college,percent_married,median_income,average_act,percent_lunch,year,state,zip_code,school_type,school_level,charter,grade_12_offered
0,100001600143,0.117962,0.445283,0.346495,42820.0,20.433455,0.066901,2016-2017,DE,19804,Regular School,High,Yes,Yes
1,100008000024,0.063984,0.662765,0.767619,89320.0,19.498168,0.112412,2016-2017,DE,19709,Regular School,High,No,Yes
2,100008000225,0.056460,0.701864,0.713090,84140.0,19.554335,0.096816,2016-2017,DE,19709,Regular School,High,No,Yes
3,100017000029,0.044739,0.692062,0.641283,56500.0,17.737485,0.296960,2016-2017,DE,19958,Regular School,High,No,Yes
4,100018000040,0.077014,0.640060,0.834402,54015.0,18.245421,0.262641,2016-2017,DE,19934,Regular School,High,No,Yes

In [27]:
# Inspect merged dataframe
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7986 entries, 0 to 7985
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 7986 non-null   object
 1   rate_unemployment  7972 non-null   float64
 2   percent_college    7973 non-null   float64
 3   percent_married    7961 non-null   float64
 4   median_income      7966 non-null   float64
 5   average_act        7986 non-null   float64
 6   percent_lunch      7986 non-null   float64
 7   year               7898 non-null   str
 8   state              7898 non-null   str
 9   zip_code           7898 non-null   object
 10  school_type        7898 non-null   str
 11  school_level       7898 non-null   str
 12  charter            7898 non-null   str
 13  grade_12_offered   7898 non-null   str
dtypes: float64(6), object(2), str(6)
memory usage: 1.1+ MB

In [28]:
# Review missing values from merged dataset
df.isna().sum()

id                    0
rate_unemployment    14
percent_college      13
percent_married      25
median_income        20
average_act           0
percent_lunch         0
year                 88
state                88
zip_code             88
school_type          88
school_level         88
charter              88
grade_12_offered     88
dtype: int64

* After the left join operation between the EdGap and school information datasets, 88 records contained missing values across all seven school information columns.

### Validate Data
This step is to ensure we handle invalid data like erroneous negative values or unrealistic values from our numerical predictors, as well as dependent variable.
We begin by reviewing descriptive statistics to identify values that may require further investigation or correction before analysis.

In [29]:
df.describe()

,rate_unemployment,percent_college,percent_married,median_income,average_act,percent_lunch
count,7972.000000,7973.000000,7961.000000,7966.000000,7986.000000,7986.000000
mean,0.098730,0.568930,0.633440,52026.905222,20.181532,0.420651
std,0.058959,0.165704,0.196764,24228.057079,2.595201,0.239754
min,0.000000,0.091493,0.000000,3589.000000,-3.070818,-0.054545
25%,0.058655,0.450828,0.523810,36597.250000,18.600000,0.238501
50%,0.085649,0.554979,0.667594,46833.500000,20.400000,0.381570
75%,0.123376,0.676571,0.777135,61369.250000,21.910867,0.575447
max,0.590278,1.000000,1.000000,226181.000000,32.362637,0.998729

* Average act and percent lunch columns have at least one negative values which may be an error.

In [30]:
# Identify invalid ACT scores
df[df['average_act'] < 1 ]

,id,rate_unemployment,percent_college,percent_married,median_income,average_act,percent_lunch,year,state,zip_code,school_type,school_level,charter,grade_12_offered
3773,341269003101,0.153491,0.284550,0.329727,23783.0,-3.070818,0.796380,2016-2017,NJ,7501,Regular School,High,No,Yes
3776,341269003107,0.126452,0.321543,0.253482,31563.0,-3.070818,0.847015,2016-2017,NJ,7505,Regular School,High,No,Yes
3777,341269003109,0.060403,0.344922,0.138728,25000.0,-3.070818,0.837104,2016-2017,NJ,7505,Regular School,High,No,Yes

3 rows have invalid average act scores

In [31]:
# Identify invalid percent lunch
df[df['percent_lunch'] < 0].head()

,id,rate_unemployment,percent_college,percent_married,median_income,average_act,percent_lunch,year,state,zip_code,school_type,school_level,charter,grade_12_offered
1398,173897003956,0.160519,0.673671,0.554577,68924.0,16.500000,-0.004777,2016-2017,IL,60473,Regular School,High,No,Yes
1422,174098004105,0.040594,0.789430,0.831663,69466.0,21.400000,-0.007792,2016-2017,IL,61571,Regular School,High,No,Yes
2336,250279000217,0.027694,0.955152,1.000000,111923.0,16.025641,-0.022670,2016-2017,MA,2116,Regular School,High,No,Yes
2514,251104001774,0.051298,0.588981,0.795222,50530.0,22.545788,-0.026866,2016-2017,MA,1257,Regular School,High,No,Yes
2718,260807004379,0.154488,0.545110,0.772984,43750.0,18.700000,-0.017241,2016-2017,MI,48604,Regular School,High,No,Yes

In [32]:
df[df['percent_lunch'] < 0]['percent_lunch'].describe()

count    20.000000
mean     -0.018152
std       0.012398
min      -0.054545
25%      -0.024275
50%      -0.015110
75%      -0.009866
max      -0.004348
Name: percent_lunch, dtype: float64

* 20 rows have incorrect percent lunch data.

### Address incorrect data 
Using df.loc[row_condition, column_name]= new_val, We will address incorrect data by overriding existing values with np.nan

In [33]:
df.loc[df['average_act'] < 1, 'average_act' ] = np.nan

In [34]:
df.loc[df['percent_lunch'] <0, 'percent_lunch'] = np.nan

Verify min max to see if the values are correct

In [35]:
df.select_dtypes(include=['number']).agg(['min', 'max']).round(2)

,rate_unemployment,percent_college,percent_married,median_income,average_act,percent_lunch
min,0.00,0.09,0.0,3589.0,12.36,0.0
max,0.59,1.00,1.0,226181.0,32.36,1.0

* We have now addressed erroneous data in average act and percent lunch.

In [36]:
numeric_cols = [
    'rate_unemployment',
    'percent_college',
    'percent_married',
    'median_income',
    'average_act',
    'percent_lunch'
]

df[numeric_cols].describe()

,rate_unemployment,percent_college,percent_married,median_income,average_act,percent_lunch
count,7972.000000,7973.000000,7961.000000,7966.000000,7983.000000,7966.000000
mean,0.098730,0.568930,0.633440,52026.905222,20.190270,0.421753
std,0.058959,0.165704,0.196764,24228.057079,2.556231,0.239042
min,0.000000,0.091493,0.000000,3589.000000,12.362637,0.000000
25%,0.058655,0.450828,0.523810,36597.250000,18.600000,0.239676
50%,0.085649,0.554979,0.667594,46833.500000,20.400000,0.382620
75%,0.123376,0.676571,0.777135,61369.250000,21.910867,0.576196
max,0.590278,1.000000,1.000000,226181.000000,32.362637,0.998729

* The numerical variables were reviewed for invalid values and potential outliers.
* All numerical variables now fall within their expected ranges.
* Some extreme observations remain, including an unemployment rate of approximately 59% and a median household income as low as $3,589.
* These observations will be retained for now and examined further during Exploratory Data Analysis (EDA.

### Inspect categorical variables
Next we will review some key categorical variables for potential analysis. We will be using some of the categorical variables for exploratory data analysis. In addition, we may use some categories in our regression models as well.

In [37]:
categorical_cols = [
    'school_type',
    'school_level',
    'charter',
    'grade_12_offered',
    'state'
]

for col in categorical_cols:
    print(f"---"*5)
    print(df[col].value_counts(dropna=False))

---------------
school_type
Regular School                 7885
NaN                              88
Alternative School               10
Special Education School          2
Career and Technical School       1
Name: count, dtype: int64
---------------
school_level
High            7230
Other            631
NaN               88
Not reported      35
Elementary         2
Name: count, dtype: int64
---------------
charter
No                7329
Yes                352
Not applicable     217
NaN                 88
Name: count, dtype: int64
---------------
grade_12_offered
Yes             7860
NaN               88
Not reported      35
No                 3
Name: count, dtype: int64
---------------
state
TX     966
OH     693
PA     601
IL     590
MI     587
FL     441
NC     416
WI     386
NY     385
GA     383
NJ     354
MO     350
IN     347
TN     309
MA     292
WA     273
LA     245
KY     216
NaN     88
WY      38
DE      26
Name: count, dtype: int64

* School type may not be usefule for categorical analysis as almost all scholls fall under "Regular School" category.
* Additionally, most schools were classified as regular high schools, with relatively few observations in other school-type categories.
* Charter status can be used as a potential categorical predictor, with 352 charter schools and 7,329 non-charter schools.
* The state of Texas has the most number of schools represented in the dataset.

Lets inspect the grade 12 offered data to see if there are schools not categorized as "High" in the school_level columns offer grade 12.

In [38]:
pd.crosstab(
    df['school_level'],
    df['grade_12_offered'],
    dropna=False
)

grade_12_offered  No  Not reported   Yes  NaN
school_level
Elementary         2             0     0    0
High               0             0  7230    0
Not reported       0            35     0    0
Other              1             0   630    0
NaN                0             0     0   88

* We do have 630 schools classified as "Other" that offer grade 12.
* Since all high schools in our dataset offer grade 12 we will filter dataset on weather school offers grade 12 for further analysis

In [39]:
df_grade_12 = df.loc[
    df['grade_12_offered'] == 'Yes'
].copy()

In [40]:
df_grade_12.info()

<class 'pandas.DataFrame'>
Index: 7860 entries, 0 to 7985
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 7860 non-null   object
 1   rate_unemployment  7846 non-null   float64
 2   percent_college    7847 non-null   float64
 3   percent_married    7836 non-null   float64
 4   median_income      7840 non-null   float64
 5   average_act        7857 non-null   float64
 6   percent_lunch      7840 non-null   float64
 7   year               7860 non-null   str
 8   state              7860 non-null   str
 9   zip_code           7860 non-null   object
 10  school_type        7860 non-null   str
 11  school_level       7860 non-null   str
 12  charter            7860 non-null   str
 13  grade_12_offered   7860 non-null   str
dtypes: float64(6), object(2), str(6)
memory usage: 1.2+ MB

In [41]:
df_grade_12['school_level'].value_counts()

school_level
High     7230
Other     630
Name: count, dtype: int64

In [42]:
df_grade_12.isna().sum().to_frame(name = 'Number of Missing Values')

                   Number of Missing Values
id                                        0
rate_unemployment                        14
percent_college                          13
percent_married                          24
median_income                            20
average_act                               3
percent_lunch                            20
year                                      0
state                                     0
zip_code                                  0
school_type                               0
school_level                              0
charter                                   0
grade_12_offered                          0

### Handle Missing values
We can either drop rows with misssing values or impute missing values

We will drop rows with missing average act scores.

In [43]:
df_grade_12.loc[
    df_grade_12['average_act'].isna()
]

,id,rate_unemployment,percent_college,percent_married,median_income,average_act,percent_lunch,year,state,zip_code,school_type,school_level,charter,grade_12_offered
3773,341269003101,0.153491,0.284550,0.329727,23783.0,NaN,0.796380,2016-2017,NJ,7501,Regular School,High,No,Yes
3776,341269003107,0.126452,0.321543,0.253482,31563.0,NaN,0.847015,2016-2017,NJ,7505,Regular School,High,No,Yes
3777,341269003109,0.060403,0.344922,0.138728,25000.0,NaN,0.837104,2016-2017,NJ,7505,Regular School,High,No,Yes

Drop rows with missing in average ACT scores using dropna method.

In [44]:
df_clean = df_grade_12.dropna(subset=['average_act']).copy()

Inspect clean data after dropping rows with missing average act scores

In [45]:
df_clean.isna().sum().to_frame(name = 'Number of Missing Values')

                   Number of Missing Values
id                                        0
rate_unemployment                        14
percent_college                          13
percent_married                          24
median_income                            20
average_act                               0
percent_lunch                            20
year                                      0
state                                     0
zip_code                                  0
school_type                               0
school_level                              0
charter                                   0
grade_12_offered                          0

### Impute data for the predictors using IterativeImputer
For the rest of the numerical predictors, we will be using sklearn's IterativeImputer to impute missing predictors

In [46]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

Create a list with all 5 numerical predictors

In [47]:
numerical_predictors = [
    'rate_unemployment',
    'percent_college',
    'percent_married',
    'median_income',
    'percent_lunch'
]

We will create two list with minimum and maximum bounds such that imputer does not impute unrealistic data. For median income, since it is not measured in percentage (0 - 1) scale, we set the max bound to np.inf (infinite).

In [48]:
min_value_list = [0,0,0,0,0] # setting minimum bounds for each of the numerical predictors
max_value_list = [1,1,1,np.inf,1] # setting max bounds for each of the numerical predictors.

In [49]:
imputer = IterativeImputer( min_value= min_value_list, max_value=max_value_list) # models the variable with missing values as a function of other variables

In [50]:
df_imputed = df_clean.copy()

In [51]:
imputer.fit(df_imputed.loc[:, numerical_predictors]) # learn the relationships between the columns

IterativeImputer(max_value=[1, 1, 1, inf, 1], min_value=[0, 0, 0, 0, 0])

In [52]:
df_clean.info()

<class 'pandas.DataFrame'>
Index: 7857 entries, 0 to 7985
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 7857 non-null   object
 1   rate_unemployment  7843 non-null   float64
 2   percent_college    7844 non-null   float64
 3   percent_married    7833 non-null   float64
 4   median_income      7837 non-null   float64
 5   average_act        7857 non-null   float64
 6   percent_lunch      7837 non-null   float64
 7   year               7857 non-null   str
 8   state              7857 non-null   str
 9   zip_code           7857 non-null   object
 10  school_type        7857 non-null   str
 11  school_level       7857 non-null   str
 12  charter            7857 non-null   str
 13  grade_12_offered   7857 non-null   str
dtypes: float64(6), object(2), str(6)
memory usage: 1.2+ MB

In [53]:
df_imputed.loc[:,numerical_predictors] = imputer.transform(df_imputed.loc[:, numerical_predictors])

In [54]:
df_imputed.info()

<class 'pandas.DataFrame'>
Index: 7857 entries, 0 to 7985
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 7857 non-null   object
 1   rate_unemployment  7857 non-null   float64
 2   percent_college    7857 non-null   float64
 3   percent_married    7857 non-null   float64
 4   median_income      7857 non-null   float64
 5   average_act        7857 non-null   float64
 6   percent_lunch      7857 non-null   float64
 7   year               7857 non-null   str
 8   state              7857 non-null   str
 9   zip_code           7857 non-null   object
 10  school_type        7857 non-null   str
 11  school_level       7857 non-null   str
 12  charter            7857 non-null   str
 13  grade_12_offered   7857 non-null   str
dtypes: float64(6), object(2), str(6)
memory usage: 1.2+ MB

In [55]:
df_imputed[numerical_predictors].agg(['min', 'max'])

,rate_unemployment,percent_college,percent_married,median_income,percent_lunch
min,0.000000,0.091493,0.0,821.792472,0.000000
max,0.590278,1.000000,1.0,226181.000000,0.998729

* All columns now have valid data

In [56]:
df_imputed[numerical_predictors].isna().sum()

rate_unemployment    0
percent_college      0
percent_married      0
median_income        0
percent_lunch        0
dtype: int64

## Export Final Data

In [57]:
df_imputed.to_csv(
    DATA_DIR / 'education_final.csv',
    encoding='utf-8-sig',
    index=False
)

## Data Preparation Summary
The data preparation process involved importing, investigating, cleaning, and merging the EdGap and school information datasets.
Relevant variables were selected and renamed using consistent naming conventions. The datasets were merged using the school id, and missing values and potentially invalid numerical observations were investigated.
Three invalid ACT scores and 20 negative free/reduced-price lunch participation values were identified. The dataset was then filtered to include schools offering grade 12.
Observations with missing ACT scores were removed, while missing numerical predictor values were imputed using `IterativeImputer`, with predefined minimum and maximum bounds to maintain data validity.
The resulting dataset contains 7,857 schools and 14 numerical and categorical variables, with no missing values in the selected analytical variables. The prepared data were exported as `education_final.csv` for exploratory data analysis and regression modeling.